### ISSUE TITLE
Works for USD but not for JPY

### ISSUE THREAD

**Issue by siberianguy** [kmn/bitflyer#1]
I'm trying to set up the real-time and it works for BTC_USD but not for BTC_JPY (I receive zero notifications). Do you have an idea why it could be the case? May be BTC_JPY is limited only to Japanese IP addresses?

**Comment by kmn** [comment]
Sorry for late response.
I am not sure but [the api document](https://lightning.bitflyer.jp/docs?lang=en) shows BTC_USD pair is available for only US account. 
So BTC_JPY may be for only JP account.
